import pandas
from fpdf import FPDF

df = pandas.read_excel('files/data.xlsx')

for index, row in df.iterrows():
    pdf= FPDF(orientation='P', unit='pt', format='A4')
    pdf.add_page()

    pdf.set_font(family='Times', style='B', size=24)
    pdf.cell(w=0, h=50, txt=row['name'], align='C',ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    txt1="PDF generated by sexy boy sudi"
    pdf.cell(w=0, h=50, txt=txt1, align='C',ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    pdf.cell(w=100, h=50, txt="Kingdom : ")
    pdf.set_font(family='Times', size=12)
    pdf.cell(w=100, h=50, txt=row['kingdom'],ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    pdf.cell(w=100, h=50, txt="Phylum : ")
    pdf.set_font(family='Times', size=12)
    pdf.cell(w=100, h=50, txt=row['phylum'],ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    pdf.cell(w=100, h=50, txt="Class : ")
    pdf.set_font(family='Times', size=12)
    pdf.cell(w=100, h=50, txt=row['class'],ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    pdf.cell(w=100, h=50, txt="Order : ")
    pdf.set_font(family='Times', size=12)
    pdf.cell(w=100, h=50, txt=row['order'],ln=1)

    pdf.set_font(family='Times', style='B', size=12)
    pdf.cell(w=100, h=50, txt="Sub Order : ")
    pdf.set_font(family='Times', size=12)
    pdf.cell(w=100, h=50, txt=row['suborder'],ln=1)


    pdf.output(f"files/animalpdf/{row['name']}.pdf")